### ISSUE TITLE
Clover report generated on server with different path doesn't work on client machine

### ISSUE THREAD

**Issue by maxromanovsky** [oker1/phpunit_codecoverage_display#10]
I have project on SMB share on *nix system mapped to Windows volume. I run phpunit on *nix server via SSH console and want to see results of code coverage in PHPStorm on my Windows machine.
Example:
- The path for the file on *nix is `/usr/local/www/project/lib/Class.php`
- This path is translated into `Z:\project\lib\Class.php` in Windows.
- I run phpunit on the server via SSH in `/usr/local/www/project/tests`
- phpunit generates clover.xml in this folder (`/usr/local/www/project/tests`)
- Inside clover.xml `/usr/local/www/project/lib/Class.php` path appears (because this is the path to the script on the server where phpunit ran)
- Path of the clover.xml  is  `Z:\project\tests\clover.xml` on Windows 
  PHPStorm does not highlight code coverage because i does not now anything about path mappings

Solution: provide configuration option to choose path mappings like:
`/usr/local/www/project` -> `Z:\project` and chose path separator (which depends on used platform)

**Comment by epoplive** [comment]
This isn't working for me, perhaps it's my setup.  I have a folder, lets call it 'repos'.  I have a bunch of repos checked out in it, with one of them being my phpstorm project.  The project has the other repos in the folder with it added as modules because this project has integration tests for the other repos.  I generate the report, I see the coverage.xml file, however PHPStorm shows 0% coverage for everything and I don't see anything in my editor.  If I edit the file and fix the paths, everything seems to work correctly.  :/

**Comment by epoplive** [comment]
I'm looking at the source code for this, and what's inside my generated coverage.xml file.  None of my nodes have an attribute named path, they all have an absolute file path in the file attribute.  I'm unfamiliar with IDEA plugins, so perhaps I just missed something?

**Comment by oker1** [comment]
I think only absolute paths work, so use those in both fields.
